import { Patient, Visit, Severity } from './types';

export const mockPatients: Patient[] = [
  {
    id: '1',
    patientId: 'VK-2025-00142',
    name: 'Ravi Kumar',
    age: 52,
    gender: 'M',
    aadhaar: '9876-5432-1012',
    language: 'Hindi',
    allergies: ['Penicillin'],
    history: [
      { date: '10 Mar 2025', diagnosis: 'Hypertension', medications: ['Amlodipine 5mg'] },
    ],
  },
  {
    id: '2',
    patientId: 'VK-2025-00138',
    name: 'Priya Mehta',
    age: 34,
    gender: 'F',
    aadhaar: '8765-4321-0987',
    language: 'English',
    allergies: [],
    history: [],
  },
  {
    id: '3',
    patientId: 'VK-2025-00145',
    name: 'Arjun Sharma',
    age: 61,
    gender: 'M',
    aadhaar: '7654-3210-9876',
    language: 'Hindi',
    allergies: ['Sulfa drugs'],
    history: [
      { date: '5 Mar 2025', diagnosis: 'Type 2 Diabetes', medications: ['Metformin 500mg'] },
    ],
  },
  {
    id: '4',
    patientId: 'VK-2025-00130',
    name: 'Nirmala Devi',
    age: 45,
    gender: 'F',
    aadhaar: '6543-2109-8765',
    language: 'Tamil',
    allergies: [],
    history: [],
  },
  {
    id: '5',
    patientId: 'VK-2025-00128',
    name: 'Karan Mehta',
    age: 28,
    gender: 'M',
    aadhaar: '5432-1098-7654',
    language: 'English',
    allergies: ['Aspirin'],
    history: [],
  },
];

export const mockVisits: Visit[] = [
  {
    id: 'v1',
    patientId: 'VK-2025-00142',
    patient: mockPatients[0],
    tokenNumber: 42,
    date: '13 Mar 2025',
    chiefComplaint: 'Chest pain radiating to left arm, fever',
    severity: 'HIGH' as Severity,
    status: 'lab-pending',
    assignedDoctor: 'Dr. Meera',
    assignedRoom: 'Room 3',
    vitals: { bp: '158/94', hr: 104, spo2: 97, temp: 38.4 },
    timeline: [
      { time: '09:41', type: 'pharmacy', title: 'Pharmacy', detail: 'Aspirin 325mg dispensed', severity: 'normal' },
      { time: '09:34', type: 'lab', title: 'Lab — CRITICAL', detail: 'Troponin 0.8 HIGH · ST Elevation', severity: 'critical' },
      { time: '09:18', type: 'consultation', title: 'Consultation', detail: 'Dr. Meera · Suspected ACS', severity: 'normal' },
      { time: '09:12', type: 'registration', title: 'Registration', detail: 'Aadhaar verified · Hindi', severity: 'normal' },
    ],
    tests: [
      {
        id: 't1', name: 'ECG', status: 'completed', orderedBy: 'Dr. Meera', orderedAt: '09:18',
        results: [{ field: 'Finding', value: 'ST Elevation', unit: '', normalRange: 'Normal sinus rhythm', flag: 'CRITICAL' }],
        flag: 'CRITICAL',
      },
      {
        id: 't2', name: 'CBC', status: 'completed', orderedBy: 'Dr. Meera', orderedAt: '09:18',
        results: [
          { field: 'WBC', value: '11.2', unit: '×10³/µL', normalRange: '4.5-11.0', flag: 'HIGH' },
          { field: 'Hb', value: '14.1', unit: 'g/dL', normalRange: '13.5-17.5', flag: 'NORMAL' },
          { field: 'Plt', value: '245', unit: '×10³/µL', normalRange: '150-400', flag: 'NORMAL' },
        ],
        flag: 'HIGH',
      },
      {
        id: 't3', name: 'Troponin I', status: 'completed', orderedBy: 'Dr. Meera', orderedAt: '09:18',
        results: [{ field: 'Troponin I', value: '0.8', unit: 'ng/mL', normalRange: '<0.04', flag: 'CRITICAL' }],
        flag: 'CRITICAL',
      },
    ],
    prescriptions: [
      { id: 'p1', drugName: 'Aspirin', dose: '325mg', frequency: 'stat, then 75mg OD', duration: '30 days', instructions: 'Take after meals', instructionLocal: 'Khana khane ke baad lein', prescribedBy: 'Dr. Meera', dispensed: true },
      { id: 'p2', drugName: 'Atorvastatin', dose: '40mg', frequency: 'OD at night', duration: '30 days', instructions: 'Take at bedtime', instructionLocal: 'Raat ko sone se pehle lein', prescribedBy: 'Dr. Meera', dispensed: false },
      { id: 'p3', drugName: 'Nitroglycerine', dose: '0.5mg SL', frequency: 'PRN', duration: 'As needed', instructions: 'Place under tongue for chest pain', instructionLocal: 'Seene mein dard hone par jeebh ke neeche rakhein', prescribedBy: 'Dr. Meera', dispensed: false },
    ],
    aiSummary: {
      narrative: 'Mr. Ravi Kumar, a 52-year-old male, presented with chest pain for 2 days with radiation to the left arm and fever. His vitals showed elevated blood pressure and heart rate. Lab results revealed critically elevated Troponin I levels and ST elevation on ECG, consistent with suspected Acute Coronary Syndrome. He was started on antiplatelet therapy and statins. Urgent cardiology referral recommended.',
      diagnosis: 'Suspected Acute Coronary Syndrome (ACS)',
      severity: 'HIGH',
      actionTaken: 'Antiplatelet therapy initiated, ECG and cardiac enzymes ordered, cardiology referral sent',
      followUpDate: '16 Mar 2025',
      referrals: [{ specialty: 'Cardiology', status: 'sent', date: '13 Mar 2025' }],
    },
  },
  {
    id: 'v2',
    patientId: 'VK-2025-00138',
    patient: mockPatients[1],
    tokenNumber: 38,
    date: '13 Mar 2025',
    chiefComplaint: 'Severe migraine, nausea',
    severity: 'MEDIUM' as Severity,
    status: 'in-consultation',
    assignedDoctor: 'Dr. Raj',
    assignedRoom: 'Room 1',
    vitals: { bp: '120/80', hr: 78, spo2: 99, temp: 36.8 },
    timeline: [
      { time: '09:15', type: 'consultation', title: 'Consultation', detail: 'Dr. Raj · Migraine evaluation', severity: 'normal' },
      { time: '08:50', type: 'registration', title: 'Registration', detail: 'Aadhaar verified · English', severity: 'normal' },
    ],
    tests: [{ id: 't4', name: 'MRI Brain', status: 'pending', orderedBy: 'Dr. Raj', orderedAt: '08:45', flag: undefined }],
    prescriptions: [],
    aiSummary: undefined,
  },
  {
    id: 'v3',
    patientId: 'VK-2025-00145',
    patient: mockPatients[2],
    tokenNumber: 45,
    date: '13 Mar 2025',
    chiefComplaint: 'Routine diabetes checkup',
    severity: 'STABLE' as Severity,
    status: 'lab-pending',
    assignedDoctor: 'Dr. Singh',
    assignedRoom: 'Room 2',
    vitals: { bp: '130/85', hr: 72, spo2: 98, temp: 36.6 },
    timeline: [
      { time: '09:00', type: 'consultation', title: 'Consultation', detail: 'Dr. Singh · Diabetes review', severity: 'normal' },
      { time: '08:35', type: 'registration', title: 'Registration', detail: 'Aadhaar verified · Hindi', severity: 'normal' },
    ],
    tests: [
      { id: 't5', name: 'HbA1c', status: 'pending', orderedBy: 'Dr. Singh', orderedAt: '08:30' },
      { id: 't6', name: 'Lipid Panel', status: 'pending', orderedBy: 'Dr. Singh', orderedAt: '08:30' },
    ],
    prescriptions: [],
  },
  {
    id: 'v4',
    patientId: 'VK-2025-00130',
    patient: mockPatients[3],
    tokenNumber: 39,
    date: '13 Mar 2025',
    chiefComplaint: 'Knee pain',
    severity: 'STABLE' as Severity,
    status: 'complete',
    assignedDoctor: 'Dr. Meera',
    timeline: [
      { time: '09:05', type: 'pharmacy', title: 'Pharmacy', detail: 'Medications dispensed', severity: 'normal' },
      { time: '08:45', type: 'consultation', title: 'Consultation', detail: 'Dr. Meera · Osteoarthritis', severity: 'normal' },
      { time: '08:30', type: 'registration', title: 'Registration', detail: 'Aadhaar verified · Tamil', severity: 'normal' },
    ],
    tests: [],
    prescriptions: [],
  },
  {
    id: 'v5',
    patientId: 'VK-2025-00128',
    patient: mockPatients[4],
    tokenNumber: 36,
    date: '13 Mar 2025',
    chiefComplaint: 'Sore throat, cough',
    severity: 'STABLE' as Severity,
    status: 'complete',
    assignedDoctor: 'Dr. Raj',
    timeline: [
      { time: '08:50', type: 'pharmacy', title: 'Pharmacy', detail: 'Medications dispensed', severity: 'normal' },
      { time: '08:30', type: 'consultation', title: 'Consultation', detail: 'Dr. Raj · Upper respiratory infection', severity: 'normal' },
      { time: '08:15', type: 'registration', title: 'Registration', detail: 'Aadhaar verified · English', severity: 'normal' },
    ],
    tests: [],
    prescriptions: [],
  },
];

export const queueData = [
  { token: 42, name: 'Ravi Kumar', room: 'Room 3', doctor: 'Dr. Meera' },
  { token: 38, name: 'Priya Mehta', room: 'Room 1', doctor: 'Dr. Raj' },
  { token: 45, name: 'Arjun Sharma', room: 'Room 2', doctor: 'Dr. Singh' },
];

export const labOptions = [
  { id: 'labA', name: 'Lab A — Ground Floor', avgWait: 12 },
  { id: 'labB', name: 'Lab B — 2nd Floor', avgWait: 4 },
];
